name = "discord-bot-cloudflare"
main = "./src/server.js"
compatibility_date="2023-05-18"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "${CONFIG_KV_NAMESPACE_ID}"
preview_id = "${CONFIG_KV_NAMESPACE_PREVIEW_ID}"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
