name = "discord-bot-cloudflare"
main = "./src/server.js"
compatibility_date="2023-05-18"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "{KV_NAMESPACE_ID_PLACEHOLDER}"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
